### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by Gryphonkin** [Menencia/ffrk-tools#3]
FYI: I love this site, it's so convenient!

I don't know if this is the place to submit missing items, but I noticed the 5* FFIX Diamond Sword and 4* FFIX Survival Vest weren't in the database.

**Comment by Menencia** [comment]
Thanks :)

Yep, it's the right place for this, I'll add them soon.

**Comment by Menencia** [comment]
Hmm. actually thought you were talking about IV missing items. Just read too fast.
Actually, the API don't return the IX items infos, so I can't add them...

**Comment by Gryphonkin** [comment]
That's strange.  There's some FF9 stuff in there, but those two i noticed as the only pieces of equipment i have missing.

**Comment by Menencia** [comment]
Black robe (IX) and White Robe (IX) have been added recently.

**Comment by Menencia** [comment]
Are you sure FFIX Survival Vest do exist ? I haven't found anything on it...

**Comment by Gryphonkin** [comment]
http://imgur.com/a/jMaDQ
http://imgur.com/KN5G5r3

Screenshots of my ff9 diamond sword and ff9 survival vest +

**Comment by Menencia** [comment]
I found this list : https://docs.google.com/spreadsheets/d/1-XhATQ06dAKQJGCAL7r4cluTNhhmRQacGqCo7NlsEKE/edit#gid=1867098264

Diamond Sword is here, but not Survival Vest... It would be great to find a list having them all...
